version: '3'
services:
  notebook:
    container_name: tf_notebook
    image: tensorflow/tensorflow:1.13.1-py3-jupyter
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    ports:
     - "0.0.0.0:8888:8888"
     - "0.0.0.0:6006:6006"
    volumes:
     - .:/tf/notebooks
     - ./data:/content/data
